-- Esquema base: um scan tem hosts, um host tem portas.
-- O scoring de risco e o baseline entram em migracoes posteriores.

CREATE TABLE scan (
    id            UUID PRIMARY KEY,
    target        VARCHAR(64)  NOT NULL,
    status        VARCHAR(16)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    started_at    TIMESTAMPTZ,
    finished_at   TIMESTAMPTZ,
    error_code    VARCHAR(64),
    error_message TEXT
);

CREATE TABLE host (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id     UUID         NOT NULL REFERENCES scan (id) ON DELETE CASCADE,
    ip          VARCHAR(45)  NOT NULL,
    hostname    VARCHAR(255),
    os_guess    VARCHAR(255),
    os_accuracy INTEGER
);

CREATE TABLE port (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id  BIGINT      NOT NULL REFERENCES host (id) ON DELETE CASCADE,
    number   INTEGER     NOT NULL,
    protocol VARCHAR(8),
    state    VARCHAR(16),
    service  VARCHAR(128),
    product  VARCHAR(255),
    version  VARCHAR(128)
);

-- Query do baseline implicito: "ultimo scan DONE deste target antes de X".
CREATE INDEX idx_scan_target_finished ON scan (target, finished_at DESC);
CREATE INDEX idx_host_scan ON host (scan_id);
CREATE INDEX idx_port_host ON port (host_id);
