-- Score de risco por host, com as razoes que o compoem.
--
-- O score e gravado (e nao recalculado na leitura) porque depende dos CVEs que o NVD
-- conhecia no momento do scan: recalcular semanas depois daria outro numero e o
-- historico deixava de ser comparavel.

ALTER TABLE host ADD COLUMN risk_score INTEGER;

-- Distingue "nao ha CVEs" de "nao foi possivel verificar": com o NVD em baixo, a
-- rede inteira pareceria segura, que e o pior erro que esta ferramenta podia cometer.
ALTER TABLE scan ADD COLUMN cve_lookup_degraded BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE risk_reason (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id     BIGINT       NOT NULL REFERENCES host (id) ON DELETE CASCADE,
    code        VARCHAR(64)  NOT NULL,
    description TEXT         NOT NULL,
    points      INTEGER      NOT NULL
);

CREATE INDEX idx_risk_reason_host ON risk_reason (host_id);
