import { describe, expect, it } from 'vitest';
import type { Host, Scan } from '../api/types';
import { demoScan } from '../mock/demoScan';
import { reportFilename, reportFor } from './markdown';

/**
 * O relatório é um documento que sai da ferramenta e vai para sítios onde a ferramenta
 * não está — um ticket, um email, um anexo. O que estes testes protegem é sobretudo o
 * que ele não pode ter: ruído, texto noutra língua, ou procedimento.
 */
function scanOf(hosts: Host[] = [], overrides: Partial<Scan> = {}): Scan {
  return {
    id: 'test', target: '192.168.1.0/24', status: 'DONE',
    createdAt: '2026-09-06T14:32:00Z', finishedAt: '2026-09-06T14:34:12Z',
    durationMs: 132000, hostsUp: hosts.length, hosts, ...overrides,
  };
}

describe('reportFor', () => {
  it('abre com o alvo, a data e o que se encontrou', () => {
    const report = reportFor(scanOf([
      { ip: '192.168.1.1', portCount: 0, riskBand: 'LOW', riskScore: 0 },
    ]));

    expect(report).toContain('# Portscape — 192.168.1.0/24');
    // Data e fuso fixos: um documento partilhado nao pode mudar com a maquina que o gerou.
    expect(report).toContain('6 September 2026 at 14:34 UTC');
    expect(report).toContain('1 device');
    expect(report).toContain('2m 12s');
  });

  it('um scan sem hosts da um documento valido, nao um erro', () => {
    const report = reportFor(scanOf([]));

    expect(report).toContain('# Portscape');
    expect(report).toContain('No devices responded.');
  });

  it('os hosts saem por risco decrescente, e o .60 nao vem antes do .9', () => {
    const report = reportFor(scanOf([
      { ip: '192.168.1.9', portCount: 0, riskScore: 10 },
      { ip: '192.168.1.60', portCount: 0, riskScore: 10 },
      { ip: '192.168.1.2', portCount: 0, riskScore: 90 },
    ]));

    const order = [...report.matchAll(/\| `(192\.168\.1\.\d+)` \|/g)].map((m) => m[1]);
    expect(order).toEqual(['192.168.1.2', '192.168.1.9', '192.168.1.60']);
  });

  it('um host sem nada a assinalar nao ganha uma seccao propria', () => {
    const report = reportFor(scanOf([
      { ip: '192.168.1.5', portCount: 0, riskScore: 0, hostname: 'quiet.lan' },
      { ip: '192.168.1.6', portCount: 1, riskScore: 35, hostname: 'noisy.lan',
        riskReasons: [{ code: 'OPEN_PORT', description: 'Port 23/tcp (telnet) open', points: 35 }],
        ports: [{ number: 23, protocol: 'tcp', state: 'open', service: 'telnet' }] },
    ]));

    expect(report).toContain('## 192.168.1.6 — noisy');
    expect(report).not.toContain('## 192.168.1.5 —');
    // Mas continua no inventario: um inventario que omite o que estava calmo nao e um
    // inventario.
    expect(report).toContain('## Nothing notable');
    expect(report).toContain('`192.168.1.5`');
  });

  it('poe o aviso de CVEs incompletos no topo, e nao numa nota de rodape', () => {
    // Num documento lido sem a aplicacao ao lado, "o risco esta subestimado" tem de ser
    // a primeira coisa que se ve.
    const report = reportFor(scanOf([{ ip: '192.168.1.1', portCount: 0 }],
      { cveLookupDegraded: true }));

    const warning = report.indexOf('CVE lookup was incomplete');
    expect(warning).toBeGreaterThan(-1);
    expect(warning).toBeLessThan(report.indexOf('## Inventory'));
  });

  it('uma barra vertical num nome nao parte a tabela', () => {
    const report = reportFor(scanOf([
      { ip: '192.168.1.1', portCount: 0, hostname: 'weird|name' },
    ]));

    expect(report).toContain('weird\\|name');
  });

  it('nao leva marca de agua, rodape, nem emoji', () => {
    const report = reportFor(demoScan);

    expect(report).not.toMatch(/generated by|gerado por|made with|powered by/i);
    expect(report).not.toMatch(/\p{Extended_Pictographic}/u);
    // Termina no conteudo e numa quebra de linha, sem despedida.
    expect(report.trimEnd().endsWith('.')).toBe(true);
  });

  it('sai todo em ingles -- as strings do backend tambem', () => {
    const report = reportFor(demoScan);

    // Um documento bilingue nao se manda a ninguem. Se o backend voltar a emitir
    // portugues, isto apanha-o.
    expect(report).not.toMatch(/\b(Porta|Fechar|Actualizar|exposta|exposto|conhecido)\b/);
  });

  it('descreve a consequencia, nunca o procedimento', () => {
    const report = reportFor(demoScan);

    expect(report).not.toMatch(/\b(payload|exploit this|run the following|brute[- ]force)\b/i);
  });

  it('a fixture da demo produz um documento completo', () => {
    const report = reportFor(demoScan);

    expect(report).toContain('## Inventory');
    expect(report).toContain('### Likely attack path');
    expect(report).toContain('### What to fix first');
    expect(report).toContain('### Open ports');
    expect(report).toContain('actively exploited');
  });
});

describe('reportFilename', () => {
  it('e estavel e ordenavel', () => {
    expect(reportFilename(scanOf())).toBe('portscape-192-168-1-0-24-2026-09-06.md');
  });

  it('aguenta um scan sem data', () => {
    expect(reportFilename(scanOf([], { createdAt: '', finishedAt: null })))
      .toBe('portscape-192-168-1-0-24-undated.md');
  });
});
